### ISSUE TITLE
Loop call? Maybe it is a mistake

### ISSUE THREAD

**Issue by Hellozaq** [cs-au-dk/jelly#18]
Hello, I had just found that there is a loop call in the output callgraph webpage. 
Afterwards, I checked the code and found that it did not exist.

The analyzed package is openbadges-issuer@0.4.0.

For example, here is one of the non-existent call edges, which is from createCache to choices.js:
![image](https://github.com/cs-au-dk/jelly/assets/24477980/e4300103-65fe-4822-89ee-c4c2dbd9fe7c)

And this is the source code of 'lodash@2.4.2:dist/lodash.js:292:3:createCache':
``` javascript
function createCache(array) {
    var index = -1,
        length = array.length,
        first = array[0],
        mid = array[(length / 2) | 0],
        last = array[length - 1];

    if (first && typeof first == 'object' &&
        mid && typeof mid == 'object' && last && typeof last == 'object') {
      return false;
    }
    var cache = getObject();
    cache['false'] = cache['null'] = cache['true'] = cache['undefined'] = false;

    var result = getObject();
    result.array = array;
    result.cache = cache;
    result.push = cachePush;

    while (++index < length) {
      result.push(array[index]);
    }
    return result;
  }
```

**Comment by amoeller** [comment]
Running Jelly with `--callgraph` does show some (possibly spurious) call edges from createCache to choices.js:

**Comment by Hellozaq** [comment]
> Running Jelly with `--callgraph` does show some (possibly spurious) call edges from createCache to choices.js:
> 
> ```
> node_modules/lodash/dist/lodash.js:294:18:294:30 -> node_modules/inquirer/lib/objects/choices.js:39:10
> node_modules/lodash/dist/lodash.js:312:7:312:32 -> node_modules/inquirer/lib/objects/choices.js:25:34
> node_modules/lodash/dist/lodash.js:312:7:312:32 -> node_modules/inquirer/lib/objects/choices.js:120:32
> node_modules/lodash/dist/lodash.js:312:7:312:32 -> node_modules/inquirer/lib/objects/choices.js:119:26
> ```

Sorry, I don't understand what you meant by "spurious". So is it a bug?
Here is the source code in node_modules/lodash/dist/lodash.js. In 294:18:294:30, it just get the length of the input array.
![image](https://github.com/cs-au-dk/jelly/assets/24477980/66cd444e-a211-4c70-94b7-75db80e36064)

**Comment by amoeller** [comment]
No, it's not a bug. Some amount of imprecision is unavoidable - determining the exact call graphs is [undecidable](https://en.wikipedia.org/wiki/Undecidable_problem).
