### ISSUE TITLE
Is this an overlooked call edge?

### ISSUE THREAD

**Issue by Hellozaq** [cs-au-dk/jelly#19]
First of all, thank you very much for your work. 

When I run jelly in foxx-framework@0.3.6, I found that there is no call edge between "yargs@5.0.0:yargs.js:13:1:Yargs" and "yargs@5.0.0:yargs.js:678:3:parseArgs", and there is also no call edge between "yargs@5.0.0:yargs.js:13:1:Yargs" and "yargs@5.0.0:yargs.js:664:10:<anonymous>", "yargs@5.0.0:yargs.js:386:16:<anonymous>", "yargs@5.0.0:yargs.js:501:19:<anonymous>", which are containing "parseArgs". 

Is this an overlooked call edge?

**Comment by amoeller** [comment]
Seems to work fine when I try. I can't reproduce your problems without more detailed knowledge of what you are doing. And I'm sorry I don't have time to help anytime soon.
