### ISSUE TITLE
Bug report: redundant method call edge in the generated callgraph

### ISSUE THREAD

**Issue by werifu** [cs-au-dk/jelly#7]
I have 3 files: index.js, mylib1.js and mylib2.js
```javascript
// index.js
const mylib1 = require('./mylib1');
const mylib2 = require('./mylib2');

const lib1 = new mylib1.MyLib1();
lib1.method();
```

```javascript
// mylib1.js
class MyLib1 {
  constructor() { }
  method() { 
    console.log('my lib1');
  }
}

module.exports = {
  MyLib1,
}
```

```javascript
// mylib2.js
class MyLib2 {
  constructor() { }
  method() { 
    console.log('my lib2');
  }
}

module.exports = {
  MyLib2,
  method() {
    console.log('isolate')
  }
}
```
After analyzing the index.js with `jelly --callgraph-html cg.html index.js`
There is a redundant edge [index.js => MyLib2.method] which is not called.
This may only happen when exporting a class, while another function `method` exported in mylib2.js is ignored correctly.

![image](https://user-images.githubusercontent.com/53432474/226188799-9f095651-806d-4d55-a96b-5439c357e7e0.png)

**Comment by werifu** [comment]
Btw, if there are multiple methods with the same name like `method()` in both `class MyLib1_1` and `class MyLib1_2` in mylib1.js, this bug still happens.

**Comment by amoeller** [comment]
This is not a bug but an imprecise result. Some objects, including class instances, are modeled using field-based analysis, which means that methods with the same name in neighboring packages are mixed together in the abstraction.
